### ISSUE TITLE
Error with subscription.start

### ISSUE THREAD

**Issue by nismot** [richard-viney/lightstreamer#2]
Trying to get this to work with FOREX.com wondering if this might be an SDK/compatibility issue. They are using Lightstreamer 7.0.3. 

So I guess my question is what SDK version is the gem built against?

```ruby
require 'lightstreamer'

session = Lightstreamer::Session.new server_url: 'https://push.cityindex.com',
                                     adapter_set: 'STREAMINGALL', username: 'x', password: 'x'

session.on_error do |error|
  raise error
end

session.connect

subscription = session.build_subscription data_adapter: 'PRICES', mode: :merge, items: ['PRICE.401484347', 'PRICE.401484392'],
                                          fields: [:MarketID, :Bid, :Offer]

queue = Queue.new

subscription.on_data do |subscription, item_name, item_data, new_data|
    queue.push item_data
  end
  
  subscription.start snapshot: true
  
  loop do
    data = queue.pop
    puts " #{data[:MarketId]} - Bid: #{data[:Bid]}, Ask: #{data[:Offer]}"
  end
```

This is returning the following error.

```
Traceback (most recent call last):
	10: from testingLS.rb:30:in `<main>'
	 9: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/subscription.rb:95:in `start'
	 8: from /Users/tomg/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
	 7: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/session.rb:288:in `control_request'
	 6: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/post_request.rb:15:in `execute'
	 5: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/post_request.rb:30:in `execute_multiple'
	 4: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/excon-0.76.0/lib/excon.rb:250:in `post'
	 3: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/excon-0.76.0/lib/excon/connection.rb:281:in `request'
	 2: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/excon-0.76.0/lib/excon/connection.rb:450:in `response'
	 1: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/excon-0.76.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
/Users/tomg/.rvm/gems/ruby-2.6.3/gems/excon-0.76.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected(200) <=> Actual(503 Service Unavailable) (Excon::Error::ServiceUnavailable)
	6: from testingLS.rb:30:in `<main>'
	5: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/subscription.rb:95:in `start'
	4: from /Users/tomg/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
	3: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/session.rb:288:in `control_request'
	2: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/post_request.rb:15:in `execute'
	1: from /Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/post_request.rb:29:in `execute_multiple'
/Users/tomg/.rvm/gems/ruby-2.6.3/gems/lightstreamer-0.16/lib/lightstreamer/post_request.rb:41:in `rescue in execute_multiple': Expected(200) <=> Actual(503 Service Unavailable) (Lightstreamer::Errors::ConnectionError)
```

**Comment by richard-viney** [comment]
This gem is written against the spec for the Lightstreamer protocol so does not use any external SDK. The stream is connecting successfully here so I don't see any evidence for a versioning problem.

The server is returning a 503 from the POST request to setup the new subscription. A 503 "indicates that the server is not ready to handle the request. Common causes are a server that is down for maintenance or that is overloaded." This is not a Lightstreamer protocol error, so that suggests that the remote server is the problem here.

**Comment by nismot** [comment]
Thanks for your response, that sounds reasonable. Do you think maybe there is a difference in protocol/parameter requirements for accepting my sub downstream trying to connect to their lightstreamer? I haven't had much time to dig into the lightstreamer side just yet, kind of moved past this at the moment. :)

**Comment by richard-viney** [comment]
I suggest:
* Looking for any documentation this provider has regarding subscriptions that they offer.
* Inspecting the network activity for a website that you know uses this Lightstreamer server to see what subscriptions it uses and how it sets them up. This happens through HTTP POST requests.
* Trying with the official Lightstreamer JavaScript client. If that works and this gem doesn't then there's likely a bug in this gem that should be addressed.

**Comment by richard-viney** [comment]
Please re-open this issue if you find a repro case that looks like a bug in this library.
